default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: blgr_dev

test:
  <<: *default
  database: blgr_dev

production:
  <<: *default
  database: blgr_dev
